/**
 * Created by Gohma on 05/06/2017.
 */
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DOUBLE_ASYNC = 'COUNTER_DOUBLE_ASYNC'

export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST'
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL'
export const FETCH_NEWS_SUCCES = 'FETCH_NEWS_SUCCES'

export const FETCH_NEWS_AGREGAT_REQUEST = 'FETCH_NEWS_AGREGAT_REQUEST'
export const FETCH_NEWS_AGREGAT_FAIL = 'FETCH_NEWS_AGREGAT_FAIL'
export const FETCH_NEWS_AGREGAT_SUCCES = 'FETCH_NEWS_AGREGAT_SUCCES'
